receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  attributes:
    actions:
      - key: TFM
        action: insert
        value: vera-naguelquin
  batch:
    timeout: 1s

  resource:
    attributes:
      - key: service.name
        value: my-service
        action: upsert
      - key: telemetry.sdk.language
        value: java
        action: upsert

exporters:
  debug:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlphttp:
    endpoint: http://loki:3100/otlp
  otlp:
    endpoint:  jaeger:4317
    tls:
      insecure: true
      
service:
  extensions: [zpages,health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [attributes,batch]
      exporters: [debug,prometheus]
    traces:
      receivers: [otlp]
      processors: [attributes,batch]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors: [attributes,batch]
      exporters: [debug, otlphttp]
      
extensions:
  zpages:
    endpoint: "0.0.0.0:55681"
  health_check:
    endpoint: "0.0.0.0:13133"