receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http: 
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
    
  kafka/traces:
    brokers: ["192.168.100.10:9092"]
    topic: "otlp_spans" 
    encoding: "otlp_proto" #otlp_proto, otlp_json,jaeger_proto
    protocol_version: 2.0.0
    metadata:
      full: false 
      
  kafka/metrics:
    brokers: ["192.168.100.10:9092"]
    topic: "otlp_metrics" 
    encoding: "otlp_proto" #otlp_proto, otlp_json
    protocol_version: 2.0.0
    metadata:
      full: false 
      
  kafka/logs:
    brokers: ["192.168.100.10:9092"]
    topic: "otlp_logs" 
    encoding: "otlp_proto" #otlp_proto, otlp_json
    protocol_version: 2.0.0
    metadata:
      full: false

service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,kafka/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,kafka/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,kafka/logs]

extensions:
  zpages:
    endpoint: "0.0.0.0:55679" 
  health_check:
    endpoint: "0.0.0.0:13133" 