receivers:

  kafka/traces:
    brokers: ["192.168.100.10:9092"] #brokers: ["kafka:9092"]
    topic: "otlp_spans"
    encoding: "otlp_proto" #otlp_proto, jaeger_proto
    protocol_version: 2.0.0
    metadata:
      full: false 
      
  kafka/metrics:
    brokers: ["192.168.100.10:9092"] #brokers: ["kafka:9092"]
    topic: "otlp_metrics"
    encoding: "otlp_proto" 
    protocol_version: 2.0.0
    metadata:
      full: false
      
  kafka/logs:
    brokers: ["192.168.100.10:9092"] #brokers: ["kafka:9092"]
    topic: "otlp_logs"
    encoding: "otlp_proto"
    protocol_version: 2.0.0
    metadata:
      full: false 

processors:
  batch:
    timeout: 1s
  resource: 
    attributes:
      - action: insert
        key: service.name
        value: "otel-kafka-processor-2"

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: "0.0.0.0:8889"
  # prometheusremotewrite:
  #   endpoint: "http://prometheus:9091/api/v1/write"
  otlphttp:
    endpoint: http://loki:3100/otlp
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  extensions: [zpages, health_check]
  pipelines:
    metrics:
      receivers: [kafka/metrics]
      processors: [batch, resource]
      exporters: [debug,prometheus]
    traces:
      receivers: [kafka/traces]
      processors: [batch, resource]
      exporters: [debug, otlp]
    logs:
      receivers: [kafka/logs]
      processors: [batch, resource]
      exporters: [debug,otlphttp]

extensions:
  zpages:
    endpoint: "0.0.0.0:55680" 
  health_check:
    endpoint: "0.0.0.0:13134"