global:
  scrape_interval: 10s  # Define cada cuánto tiempo Prometheus extrae métricas

scrape_configs:
  - job_name: "otel-collector-2"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector-2:8889"]
      

# remote_write:
#   - url: "http://prometheus:9091/api/v1/write"
